POST http://localhost:8080/api/account/login

{
  "username_or_email": "coder2k",
  "password": "Coder2k123!"
}

###

POST localhost:8080/api/dashboard/speaker/event/1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="photo.jpg"
Content-Type: image/jpeg

< D:\test_image.jpeg
--boundary
Content-Disposition: form-data; name="json"

{
  "name": "coder2k",
  "short_bio": "Meine Kurzbiografie",
  "bio": "Meine Biografie",
  "photo_x": 50,
  "photo_y": 50,
  "photo_size": 100,
}

--boundary--

###
