POST http://localhost:8080/api/account/login

{
  "username_or_email": "coder2k",
  "password": "Coder2k123!"
}

###

POST localhost:8080/api/dashboard/speaker/event/1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="photo.jpg"
Content-Type: image/jpeg

< C:\Users\micha\Pictures\coder2k\coder2k-2024-09-26-quadratisch.jpg
--boundary
Content-Disposition: form-data; name="json"

{
  "photo_x": 200,
  "photo_y": 50,
  "photo_size": 600
}

--boundary--

###
