POST http://localhost:8080/api/account/login

{
  "username_or_email": "coder2k",
  "password": "Coder2k123!"
}

###

PUT localhost:8080/api/account/change-email

{
    "password": "Coder2k123!",
    "email": "coder@2k.com"
}
