POST http://localhost:8080/api/account/login

{
  "username_or_email": "coder2k",
  "password": "Coder2k123!"
}

###

PUT localhost:8080/api/account/change-password

{
    "old_password": "Coder2k123!",
    "new_password": "Coder4k123!"
}
