POST http://localhost:8080/api/account/login

{
  "username_or_email": "coder2k",
  "password": "password"
}

###

POST localhost:8080/api/dashboard/speaker/submit-talk/1

{
    "title": "Programmieren wie ein Profi",
    "description": "In diesem Vortrag lernst du, wie du professionell programmierst.",
    "tag_ids": [5, 1, 3],
    "possible_durations": [30, 45, 60],
    "notes": "Ich kann nur am zweiten Tag der Konferenz."
}
