POST http://localhost:8080/api/account/login

{
  "username_or_email": "coder2k",
  "password": "password"
}

###

PUT localhost:8080/api/dashboard/admin/talk/10/suggest-time-slot

{
    "time_slot_id": 10
}
