POST http://localhost:8080/api/account/login

{
  "username_or_email": "ClausKleber",
  "password": "ClausKleber123!"
}

###

POST localhost:8080/api/dashboard/user/apply-as-speaker
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="photo.jpg"
Content-Type: image/jpeg

< D:\Claus Kleber.jpg
--boundary
Content-Disposition: form-data; name="json"

{
  "name": "Claus Kleber",
  "short_bio": "Meine Kurzbiografie",
  "bio": "Meine Biografie",
  "photo_x": 100,
  "photo_y": 20,
  "photo_size": 400,
    "social_media_links": [
        {
          "social_media_type_id": 7,
          "url": "https://twitter.com/ClausKleber"
        },
        {
          "social_media_type_id": 1,
          "url": "https://facebook.com/ClausKleber"
        }
    ]
}

--boundary--

###
