POST http://localhost:8080/api/account/login

{
  "username_or_email": "coder2k",
  "password": "password"
}

### Update two links, change second link from GitHub to GitLab

PUT localhost:8080/api/dashboard/user/social-media-link

{
  "social_media_links": [
    {
      "id": 1,
      "social_media_type_id": 2,
      "url": "https://www.twitch.tv/theReal_coder2kHD"
    },
    {
      "id": 2,
      "social_media_type_id": 10,
      "url": "https://www.gitlab.com/coder2k"
    }
  ]
}
