POST http://localhost/api/account/login

{
  "username_or_email": "coder2k",
  "password": "Coder2k123!"
}

###

POST localhost/api/dashboard/admin/event/new

{
    "title": "TECH STREAM CONFERENCE 2025",
    "subtitle": "New Event Subtitle",
    "description": "New Event Description",
    "start_date": "2025-11-05",
    "end_date": "2025-11-06",
    "discord_url": "https://discord.gg/123456",
    "twitch_url": "https://twitch.tv/123456",
    "presskit_url": "https://presskit.com/123456",
    "trailer_url": "https://www.youtube.com/watch?v=123456",
    "trailer_poster_url": "https://img.youtube.com/vi/123456/maxresdefault.jpg",
    "description_headline": "New Event Description Headline",
    "schedule_visible_from": null,
    "publish_date": null,
    "frontpage_date": "2025-03-19 18:00:00"
}
