POST http://localhost/api/account/login

{
  "username_or_email": "coder2k",
  "password": "Coder2k123!"
}

###

POST localhost/api/dashboard/admin/video-room/event/1

{
  "base_url": "https://vdo.ninja"
}
